<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<!-- THIS IS WHAT YOU NEED TO ADD -->
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.*" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.*" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.*" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.*" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.*" />
		<PackageReference Include="Razorpay" Version="3.3.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TradingAlpha.Application\TradingAlpha.Application.csproj" />
		<ProjectReference Include="..\TradingAlpha.Domain\TradingAlpha.Domain.csproj" />
	</ItemGroup>

</Project>